hsv_filter_node:
  ros__parameters:
    use_sim_time: true
    min_h: 64
    max_h: 96
    min_s: 145
    max_s: 188
    min_v: 85
    max_v: 220

# hsv_filter_node:
#   ros__parameters:
#     use_sim_time: true
#     min_h: 41
#     max_h: 55
#     min_s: 184
#     max_s: 255
#     min_v: 193
#     max_v: 255

detection_to_3d_from_depth_node:
  ros__parameters:
    use_sim_time: true


